# permissions for end users to edit hwoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hwoperator-editor-role
rules:
- apiGroups:
  - hwoperator.com
  resources:
  - hwoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hwoperator.com
  resources:
  - hwoperators/status
  verbs:
  - get
